"""M1 core schema

Revision ID: c6fca63ba48f
Revises: 
Create Date: 2026-09-19 00:03:35.962377

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

from app.core.config import settings

# ★ pgvector 硬限制：HNSW / IVFFlat 索引最多 2000 维。
# 当前环境的 EMBEDDING_DIM=2048（volcengine doubao-embedding-vision）超限，
# 因此向量索引必须条件化创建。超过上限时走全表扫描，或先降维（见 docs/05 §4.8）。
VECTOR_INDEX_MAX_DIM = 2000
from sqlalchemy.dialects import postgresql

revision: str = 'c6fca63ba48f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_clusters',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'merged', 'closed', name='cluster_status'), server_default='open', nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_clusters'))
    )
    if settings.EMBEDDING_DIM <= VECTOR_INDEX_MAX_DIM:
        op.create_index('ix_news_clusters_centroid', 'news_clusters', ['centroid'], unique=False, postgresql_using='hnsw', postgresql_ops={'centroid': 'vector_cosine_ops'})
    op.create_index('ix_news_clusters_last_seen', 'news_clusters', ['last_seen_at'], unique=False)
    op.create_table('tags',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], name=op.f('fk_tags_parent_id_tags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name=op.f('uq_tags_slug'))
    )
    op.create_index('ix_tags_dimension', 'tags', ['dimension'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('plan', sa.Text(), server_default='free', nullable=False),
    sa.Column('quota', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('agent_runs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('graph', sa.Enum('ingest', 'review', 'compose', 'research', 'enrich', name='run_graph'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'waiting_human', 'succeeded', 'failed', 'cancelled', name='run_status'), server_default='queued', nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('interrupt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_output', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trace_url', sa.Text(), nullable=True),
    sa.Column('artifact_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_runs_parent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued','running','waiting_human')"))
    op.create_index('ix_agent_runs_thread', 'agent_runs', ['thread_id'], unique=False)
    op.create_index('ix_agent_runs_user_time', 'agent_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('source_connectors',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('connector_type', sa.Enum('tushare', 'rss', 'wechat_mp', 'weibo', 'xueqiu', 'exchange', 'news_site', 'custom_api', 'manual', name='connector_type'), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'error', 'disabled', name='connector_status'), server_default='active', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('credentials_ref', sa.Text(), nullable=True),
    sa.Column('capability', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('schedule_cron', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_source_connectors_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_connectors'))
    )
    op.create_index('ix_source_connectors_next_run', 'source_connectors', ['status', 'next_run_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_source_connectors_owner_key', 'source_connectors', ['owner_id', 'key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND owner_id IS NOT NULL'))
    op.create_index('uq_source_connectors_platform_key', 'source_connectors', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND owner_id IS NULL'))
    op.create_table('user_interests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('polarity', sa.Text(), server_default='include', nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.000', nullable=False),
    sa.Column('origin', sa.Text(), server_default='user', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interests')),
    sa.UniqueConstraint('user_id', 'dimension', 'value', name='uq_user_interests')
    )
    op.create_index('ix_user_interests_user', 'user_interests', ['user_id', 'dimension'], unique=False)
    op.create_table('agent_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.Text(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('token_input', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_output', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps')),
    sa.UniqueConstraint('run_id', 'seq', name='uq_agent_steps')
    )
    op.create_index('ix_agent_steps_run', 'agent_steps', ['run_id', 'seq'], unique=False)
    op.create_table('raw_documents',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('flash', 'article', 'announcement', 'policy', 'research_report', 'interactive_qa', 'social_post', 'market_data', name='content_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], name=op.f('fk_raw_documents_connector_id_source_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_documents')),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_raw_documents_connector_external')
    )
    op.create_index('ix_raw_documents_normalized', 'raw_documents', ['normalized_at'], unique=False, postgresql_where=sa.text('normalized_at IS NULL'))
    op.create_index('ix_raw_documents_published', 'raw_documents', ['published_at'], unique=False)
    op.create_table('sync_runs',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='sync_status'), server_default='running', nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inserted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deduped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_segments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], name=op.f('fk_sync_runs_connector_id_source_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index('ix_sync_runs_connector_started', 'sync_runs', ['connector_id', 'started_at'], unique=False)
    op.create_index('ix_sync_runs_running', 'sync_runs', ['status'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_table('usage_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_output', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('occurred_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_usage_records_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_index('ix_usage_records_category', 'usage_records', ['category', 'occurred_on'], unique=False)
    op.create_index('ix_usage_records_user_day', 'usage_records', ['user_id', 'occurred_on'], unique=False)
    op.create_table('news_items',
    sa.Column('raw_document_id', sa.UUID(), nullable=True),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('flash', 'article', 'announcement', 'policy', 'research_report', 'interactive_qa', 'social_post', 'market_data', name='content_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('lang', sa.Text(), server_default='zh', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('is_cluster_rep', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('importance', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('market_scope', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('raw_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enrich_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], name=op.f('fk_news_items_cluster_id_news_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], name=op.f('fk_news_items_connector_id_source_connectors')),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], name=op.f('fk_news_items_raw_document_id_raw_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_items')),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_news_items_connector_external'),
    sa.UniqueConstraint('content_hash', name='uq_news_items_content_hash')
    )
    op.create_index('ix_news_items_cluster', 'news_items', ['cluster_id'], unique=False)
    if settings.EMBEDDING_DIM <= VECTOR_INDEX_MAX_DIM:
        op.create_index('ix_news_items_embedding', 'news_items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_news_items_enrich', 'news_items', ['enrich_status'], unique=False, postgresql_where=sa.text("enrich_status <> 'done'"))
    op.create_index('ix_news_items_entities', 'news_items', ['entities'], unique=False, postgresql_using='gin')
    op.create_index('ix_news_items_importance', 'news_items', ['importance', 'published_at'], unique=False)
    op.create_index('ix_news_items_industries', 'news_items', ['industries'], unique=False, postgresql_using='gin')
    op.create_index('ix_news_items_keywords', 'news_items', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('ix_news_items_market_scope', 'news_items', ['market_scope'], unique=False, postgresql_using='gin')
    op.create_index('ix_news_items_published', 'news_items', ['published_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_news_items_simhash', 'news_items', ['simhash'], unique=False)
    op.create_index('ix_news_items_title_trgm', 'news_items', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_news_items_type_published', 'news_items', ['content_type', 'published_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('news_item_relations',
    sa.Column('from_news_id', sa.UUID(), nullable=False),
    sa.Column('to_news_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['from_news_id'], ['news_items.id'], name=op.f('fk_news_item_relations_from_news_id_news_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_news_id'], ['news_items.id'], name=op.f('fk_news_item_relations_to_news_id_news_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_item_relations')),
    sa.UniqueConstraint('from_news_id', 'to_news_id', 'relation', name='uq_news_item_relations')
    )
    op.create_index('ix_news_item_relations_to', 'news_item_relations', ['to_news_id'], unique=False)
    op.create_table('news_item_symbols',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('ts_code', sa.Text(), nullable=False),
    sa.Column('symbol_name', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Text(), server_default='stock', nullable=False),
    sa.Column('relation', sa.Text(), server_default='mention', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), server_default='1.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], name=op.f('fk_news_item_symbols_news_item_id_news_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_item_symbols')),
    sa.UniqueConstraint('news_item_id', 'ts_code', 'relation', name='uq_news_item_symbols')
    )
    op.create_index('ix_news_item_symbols_news', 'news_item_symbols', ['news_item_id'], unique=False)
    op.create_index('ix_news_item_symbols_ts_code', 'news_item_symbols', ['ts_code', 'created_at'], unique=False)
    op.create_table('news_item_tags',
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), server_default='1.00', nullable=False),
    sa.Column('source', sa.Text(), server_default='model', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], name=op.f('fk_news_item_tags_news_item_id_news_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_news_item_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_item_tags')),
    sa.UniqueConstraint('news_item_id', 'tag_id', name='uq_news_item_tags')
    )
    op.create_index('ix_news_item_tags_tag', 'news_item_tags', ['tag_id', 'created_at'], unique=False)
    op.create_table('user_news_actions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('news_item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('read', 'star', 'unstar', 'rate', 'hide', 'block_source', name='action_type'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 5', name=op.f('ck_user_news_actions_ck_user_news_actions_rating')),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], name=op.f('fk_user_news_actions_news_item_id_news_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_news_actions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_news_actions'))
    )
    op.create_index('ix_user_news_actions_news', 'user_news_actions', ['news_item_id'], unique=False)
    op.create_index('ix_user_news_actions_user_time', 'user_news_actions', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_user_news_actions_state', 'user_news_actions', ['user_id', 'news_item_id', 'action'], unique=True, postgresql_where=sa.text("action <> 'read'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_news_actions_state', table_name='user_news_actions', postgresql_where=sa.text("action <> 'read'"))
    op.drop_index('ix_user_news_actions_user_time', table_name='user_news_actions')
    op.drop_index('ix_user_news_actions_news', table_name='user_news_actions')
    op.drop_table('user_news_actions')
    op.drop_index('ix_news_item_tags_tag', table_name='news_item_tags')
    op.drop_table('news_item_tags')
    op.drop_index('ix_news_item_symbols_ts_code', table_name='news_item_symbols')
    op.drop_index('ix_news_item_symbols_news', table_name='news_item_symbols')
    op.drop_table('news_item_symbols')
    op.drop_index('ix_news_item_relations_to', table_name='news_item_relations')
    op.drop_table('news_item_relations')
    op.drop_index('ix_news_items_type_published', table_name='news_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_news_items_title_trgm', table_name='news_items', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_news_items_simhash', table_name='news_items')
    op.drop_index('ix_news_items_published', table_name='news_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_news_items_market_scope', table_name='news_items', postgresql_using='gin')
    op.drop_index('ix_news_items_keywords', table_name='news_items', postgresql_using='gin')
    op.drop_index('ix_news_items_industries', table_name='news_items', postgresql_using='gin')
    op.drop_index('ix_news_items_importance', table_name='news_items')
    op.drop_index('ix_news_items_entities', table_name='news_items', postgresql_using='gin')
    op.drop_index('ix_news_items_enrich', table_name='news_items', postgresql_where=sa.text("enrich_status <> 'done'"))
    op.drop_index('ix_news_items_embedding', table_name='news_items', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_news_items_cluster', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_usage_records_user_day', table_name='usage_records')
    op.drop_index('ix_usage_records_category', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_sync_runs_running', table_name='sync_runs', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_sync_runs_connector_started', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('ix_raw_documents_published', table_name='raw_documents')
    op.drop_index('ix_raw_documents_normalized', table_name='raw_documents', postgresql_where=sa.text('normalized_at IS NULL'))
    op.drop_table('raw_documents')
    op.drop_index('ix_agent_steps_run', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_user_interests_user', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index('uq_source_connectors_platform_key', table_name='source_connectors', postgresql_where=sa.text('deleted_at IS NULL AND owner_id IS NULL'))
    op.drop_index('uq_source_connectors_owner_key', table_name='source_connectors', postgresql_where=sa.text('deleted_at IS NULL AND owner_id IS NOT NULL'))
    op.drop_index('ix_source_connectors_next_run', table_name='source_connectors', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('source_connectors')
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_table('notifications')
    op.drop_index('ix_agent_runs_user_time', table_name='agent_runs')
    op.drop_index('ix_agent_runs_thread', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs', postgresql_where=sa.text("status IN ('queued','running','waiting_human')"))
    op.drop_table('agent_runs')
    op.drop_table('users')
    op.drop_index('ix_tags_dimension', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_news_clusters_last_seen', table_name='news_clusters')
    op.drop_index('ix_news_clusters_centroid', table_name='news_clusters', postgresql_using='hnsw', postgresql_ops={'centroid': 'vector_cosine_ops'})
    op.drop_table('news_clusters')
    # ### end Alembic commands ###
